// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsgnlgperdiwptfbsnkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zZ25sZ3BlcmRpd3B0ZmJzbmtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxNzAxNTEsImV4cCI6MjA3Nzc0NjE1MX0.fXQZCsqcz87AAPYhbfwk99CaciK1rXcxpsZ_9lxXvis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});